### ISSUE TITLE
"rustls" feature now depends on "native-tls"

### ISSUE THREAD

**Issue by davegallant** [gsquire/sendgrid-rs#75]
`0.11.3` did not have a dependency on "openssl":

```toml
[dependencies]
sendgrid = { version = "0.11.3", features = ["rustls"] }
```

```console
❯ cargo tree -i -p native-tls
error: package ID specification `native-tls` matched no packages
```

Now with `0.13.0`:
```toml
[dependencies]
sendgrid = { version = "0.13.0", features = ["rustls"] }
```

There is a dependency upon "native-tls":
```console
❯ cargo tree -i -p native-tls
native-tls v0.2.4
├── hyper-tls v0.4.3
│   └── reqwest v0.10.8
│       └── sendgrid v0.13.0
│           └── sendgrid-rs-issue v0.1.0 (/tmp/rust-sendgrid)
├── reqwest v0.10.8 (*)
└── tokio-tls v0.3.1
    ├── hyper-tls v0.4.3 (*)
    └── reqwest v0.10.8 (*)
```

It is no longer possible to cross-compile `sendgrid-rs` to `x86_64-unknown-linux-musl`.
